PROGRAM CSCAN_GPR_EW

USE MD_BASIC
USE MD_FFT_IFFT
USE MD_FFT_HILBERT
USE MD_FILTER
USE MD_MVMEAN
USE MD_INTERPRE
USE MD_MEAN_ASCAN

IMPLICIT NONE

!USE GSSI_PROGRAM
INCLUDE "IN_OUT_PATH_CSCAN.h"
INCLUDE "VARIABLES_CSCAN_EW.h"
INCLUDE "READ_FILES_CSCAN_EW.h"
INCLUDE "OPEN_WRITE_CSCAN.h"


!FK TRANSFORMATION
INCLUDE "FFT.h"
INCLUDE "HILBERT.h"


!CALCULATE POWER SPECTRAL DENSITY
CALL psd(f_real, f_imag, DIS, TRA, ROWS, f_psd)
!PRINT *, "PSD END"
CALL powerdb(1, f_psd, DIS, TRA, ROWS, f_pdB)
!PRINT *, "dB END"

!INCLUDE "HIGH_PASS_40.h"


!CALL psd(hpf_real, hpf_imag, DIS, TRA, ROWS, hpf_psd)
!PRINT *, "PSD END"
!CALL powerdb(1, hpf_psd, DIS, TRA, ROWS, hpf_pdB)
!PRINT *, "dB END"


!INCLUDE "BAND_PASS.h"
!INCLUDE "GAIN_CONTROL.h"


!!DO Z = 1, ROWS
!CALCULATE THE MEAN
!!      SLICE_MEAN = SUM(HILBERT_B_SCAN(:,:,ROWS))/ SIZE(HILBERT_B_SCAN(:,:,ROWS))
 
!REMOVE THE BACKGROUND
!!     HILBERT_B_SCAN(:,:,ROWS) = HILBERT_B_SCAN(:,:,ROWS) - SLICE_MEAN
!!END DO

INCLUDE "OUTPUT_A_SCAN.h"      !20
INCLUDE "OUTPUT_B_SCAN.h"      !30
!INCLUDE "OUTPUT_C_SCAN.h"      !40
!!INCLUDE "OUTPUT_FFT.h"        !50
!INCLUDE "OUTPUT_HILBERT.h"    !60
!INCLUDE "OUTPUT_PHASE.h"      !70
!INCLUDE "OUTPUT_FILTER.h"     !80


END PROGRAM
