!=======INSTANTNEOUS PHASE=============================================
!THIS CODE CALCULATES THE PAHSE FROM -PI/2.0 TO PI/2.0.
DO Z = 1, ROWS
DO Y = 1, TRA
   INST_PHASE(1,Y,Z) = ATAN(HILBERT_STACKED_B_SCAN(1,Y,Z)/STACKED_B_SCAN(1,Y,Z))
END DO 
END DO 


!SECOND QUADRANT IN COMPLEX DIAGRAM
DO Z = 1, ROWS
DO Y = 1, TRA
   IF(HILBERT_STACKED_B_SCAN(1,Y,Z) > 0.0 .AND. STACKED_B_SCAN(1,Y,Z) < 0.0) THEN
      INST_PHASE(1,Y,Z) = INST_PHASE(1,Y,Z) + PI  
   END IF     
END DO 
END DO 

!THIRD QUADRANT IN COMPLEX DIAGRAM
DO Z = 1, ROWS
DO Y = 1, TRA
   IF(HILBERT_STACKED_B_SCAN(1,Y,Z) < 0.0 .AND. STACKED_B_SCAN(1,Y,Z) < 0.0) THEN
      INST_PHASE(1,Y,Z) = INST_PHASE(1,Y,Z) + PI  
   END IF     
END DO 
END DO 

!FORTH QUADRANT IN COMLEX DIAGRAM
DO Z = 1, ROWS
DO Y = 1, TRA
   IF(HILBERT_STACKED_B_SCAN(1,Y,Z) < 0.0 .AND. STACKED_B_SCAN(1,Y,Z) > 0.0) THEN
      INST_PHASE(1,Y,Z) = INST_PHASE(1,Y,Z) + 2.0 * PI  
   END IF     
END DO 
END DO 

DO Z = 1, ROWS
DO Y = 1, TRA
   INST_PHASE2(1,Y,Z) = INST_PHASE(1,Y,Z) * 180.0/PI
END DO 
END DO 

DO Z = 1, ROWS
   WRITE(60,*) (INST_PHASE2(1,Y,Z), Y = 1, TRA)
END DO
PRINT *, "COMPLETE TO PRINT INSTANTNEOUS PHASE"
!=========================================================

!===================INSTANTNEOUS_FREQUENCY==================
 DEPTH = 100.0
 PER = 16.0
 TIME_WIN = 2.0 * DEPTH / (C/sqrt(per))
 PRINT *, "TIME_WINDOW",TIME_WIN
 
 SAMPLE_TIME = TIME_WIN / 4096.0
 
 DO Z = 1, ROWS-1
 DO Y = 1, TRA
    INST_FREQUENCY(1,Y,Z) = ( INST_PHASE2(1,Y,Z+1)-INST_PHASE2(1,Y,Z) ) / SAMPLE_TIME
 END DO
 END DO
 
 DO Z = 1, ROWS
    WRITE(61,*) (INST_FREQUENCY(1,Y,Z), Y =  TRA,1,-1)
    !WRITE(61,*) (INST_FREQUENCY(1,Y,Z), Y =  1, TRA)
 END DO
 PRINT *, "COMPLETE TO PRINT INSTANTNEOUS FREQUENCY"

