PROGRAM GEOMETRIC_COR
IMPLICIT NONE


CHARACTER (LEN=255) :: COMMON_PATH
CHARACTER (LEN=4) :: LOCAL_PATH
CHARACTER (LEN=4) :: LOCAL_PATH2

CHARACTER (LEN=255) :: INPUT_PATH
CHARACTER (LEN=255) :: INPUT_PATH2
CHARACTER (LEN=255) :: INPUT_PATH3
CHARACTER (LEN=255) :: INPUT_PATH4
CHARACTER (LEN=50) :: INPUT_NAME
CHARACTER (LEN=50) :: INPUT_NAME2

CHARACTER (LEN=255) :: OUTPUT_PATH
CHARACTER (LEN=255) :: OUTPUT_PATH2
CHARACTER (LEN=50) :: OUTPUT_NAME
CHARACTER (LEN=50) :: OUTPUT_NAME2


!==============MALA================
!INTEGER, PARAMETER :: DIS =        !X
!INTEGER, PARAMETER :: TRA =        !Y
!INTEGER, PARAMETER :: ROW =        !Z
!==================================

!==============GNSS================
INTEGER, PARAMETER :: GNSS_R = 537
INTEGER, PARAMETER :: GNSS_C = 4
!==================================

COMMON_PATH = "/home/changwan/GPR_DATA/MOGOD/2022/Site-1/"
LOCAL_PATH = "250/"
LOCAL_PATH2 = "GPS/"

INPUT_PATH = TRIM(COMMON_PATH)//LOCAL_PATH
INPUT_PATH2 = TRIM(COMMON_PATH)//LOCAL_PATH2

INPUT_NAME = "BSCAN_GPR_rmbgr_GC.txt"
INPUT_NAME2 = "elevation_fortran.txt"

INPUT_PATH3 = TRIM(INPUT_PATH)//INPUT_NAME
INPUT_PATH4 = TRIM(INPUT_PATH2)//INPUT_NAME2


PRINT *, INPUT_PATH3
PRINT *, INPUT_PATH4

END PROGRAM GEOMETRIC_COR
