PROGRAM CSCAN_GPR_NS

USE MD_BASIC
USE MD_INTERPRE

IMPLICIT NONE

!USE GSSI_PROGRAM
INCLUDE "IN_OUT_PATH_CSCAN.h"
INCLUDE "VARIABLES_CSCAN.h"
INCLUDE "READ_FILES_CSCAN.h"
INCLUDE "OPEN_WRITE_CSCAN.h"
 
!DO Y = 1, TRA
!   CALL power_pick(B_SCAN_IMAGE6(:,YY,:), DIS, TRA, ROWS, H_X, H_Z, i_h)
!END DO 

YY = 17


PRINT*,  "COMPLETED TO PICK HOROZIN_1"
PRINT*, "WRITE OUT THE RESULTS"
PRINT*, "WAITING..."

INCLUDE "OUTPUT_A_SCAN.h"      !20
INCLUDE "OUTPUT_B_SCAN.h"      !30
!INCLUDE "OUTPUT_C_SCAN.h"     !40
INCLUDE "OUTPUT_MSR_H.h"       !91 MOST STRONG RESPONSE HORIZON

INCLUDE "OUTPUT_UCF_H.h"       !90 UNCONFORMITY HORIZON
INCLUDE "OUTPUT_SHOULDER.h"    !92 PICK SHOULDER


END PROGRAM
