ALLOCATE(B_SCAN_IMAGE(ROWS,DIS,TRA), STAT=ALLOCATESTATUS)
IF (ALLOCATESTATUS /= 0) STOP "***NOT ENOUGH MEMORY***"

ALLOCATE(B_SCAN_IMAGE2(ROWS,DIS,TRA), STAT=ALLOCATESTATUS)
IF (ALLOCATESTATUS /= 0) STOP "***NOW ENOUGH MEMORY***"

ALLOCATE(B_SCAN_IMAGE3(DIS,TRA,ROWS), STAT=ALLOCATESTATUS)
IF (ALLOCATESTATUS /= 0) STOP "***NOW ENOUGH MEMORY***"




