ALLOCATE(B_SCAN_IMAGE(ROWS,DIS), STAT=ALLOCATESTATUS)
IF (ALLOCATESTATUS /= 0) STOP "***NOT ENOUGH MEMORY***"

ALLOCATE(B_SCAN_IMAGE2(ROWS,DIS), STAT=ALLOCATESTATUS)
IF (ALLOCATESTATUS /= 0) STOP "***NOW ENOUGH MEMORY***"

ALLOCATE(B_SCAN_IMAGE3(ROWS,DIS), STAT=ALLOCATESTATUS)
IF (ALLOCATESTATUS /= 0) STOP "***NOW ENOUGH MEMORY***"


