CHARACTER (LEN=13) :: FH1 = '201022_2__'
CHARACTER (LEN=4)  :: FT = '.DZT'
CHARACTER (LEN=17) :: ITEM_NUMBER

DO G=1,TRA


!=====AUTOMATIC CHANCE CODE FOR OPENING FILE===================

   IF(G<=9.AND.G>=1) THEN

     WRITE(FH1(11:11), FMT='(I1)') 0
     WRITE(FH1(12:12), FMT='(I1)') 0
     WRITE(FH1(13:13), FMT='(I1)') G
   
   ELSE IF(G<=99.AND.G>=10) THEN
    
     WRITE(FH1(11:11), FMT='(I1)') 0
     WRITE(FH1(12:13), FMT='(I2)') G
   
   ELSE

     WRITE(FH1(11:13), FMT='(I3)') G
   END IF

   ITEM_NUMBER=TRIM(FH1//FT)


!=============================PATH===================================

!COMMON_PATH1="/home/changwan/GPR/20211022/"
!COMMON_PATH2="/home/changwan/GPR/20211022/"

!COMMON_PATH1="/home/changwan/GPR/20211022_2/"
!COMMON_PATH2="/home/changwan/GPR/20211022_2/"
COMMON_PATH1="/mnt/l/GPR_DATA/20211022_2/"
COMMON_PATH2="/mnt/l/GPR_DATA/20211022_2/"


OUTPUT_NAME1="A_SCOPE_GPR.txt"
OUTPUT_NAME2="A_SCOPE_GPR_BGR.txt"
OUTPUT_NAME3="B_SCAN_IMAGE_GPR.txt"
OUTPUT_NAME4="STACKED_A_SCOPE.txt"
OUTPUT_NAME5="FFT_STACKED_A_GPR.txt"
OUTPUT_NAME6="HILBERT_A_GPR.txt"
OUTPUT_NAME7="HILBERT_STACKED_A_GPR.txt"
OUTPUT_NAME8="DFT_STACKED_A_GPR.txt"
OUTPUT_NAME9="CRRL_STACKED_HILBERT.txt"
OUTPUT_NAME10="STACKED_B_SCAN.txt"



INPUT_PATH = TRIM(COMMON_PATH1)//ITEM_NUMBER
OUTPUT_PATH1 = TRIM(COMMON_PATH2)//OUTPUT_NAME1
OUTPUT_PATH2 = TRIM(COMMON_PATH2)//OUTPUT_NAME2
OUTPUT_PATH3 = TRIM(COMMON_PATH2)//OUTPUT_NAME3
OUTPUT_PATH4 = TRIM(COMMON_PATH2)//OUTPUT_NAME4
OUTPUT_PATH5 = TRIM(COMMON_PATH2)//OUTPUT_NAME5
OUTPUT_PATH6 = TRIM(COMMON_PATH2)//OUTPUT_NAME6
OUTPUT_PATH7 = TRIM(COMMON_PATH2)//OUTPUT_NAME7
OUTPUT_PATH8 = TRIM(COMMON_PATH2)//OUTPUT_NAME8
OUTPUT_PATH9 = TRIM(COMMON_PATH2)//OUTPUT_NAME9
OUTPUT_PATH10 = TRIM(COMMON_PATH2)//OUTPUT_NAME10
!=====================================================================


OPEN(UNIT=10, FILE=INPUT_PATH, FORM='UNFORMATTED', ACCESS='STREAM', STATUS='OLD', ACTION='READ')

      READ(10) HEADER, B_SCAN_IMAGE(:,:,G)

!INTEGER => REAL*8
      B_SCAN_IMAGE2(:,:,G) = B_SCAN_IMAGE(:,:,G)

      PRINT *, "G=",G    

DO X = 1, DIS
  DO Y = 1, TRA
    DO Z = 1, ROWS

       B_SCAN_IMAGE3(X,Y,Z) = B_SCAN_IMAGE2(Z,X,Y)

!      PRINT *, X,Y,Z,"<----",Z,X,Y

    END DO
  END DO
END DO
 
CLOSE(10)

END DO


