PROGRAM B_SCAN_GPR

USE MD_BACKGROUND
USE MD_REMOVE_MEAN

IMPLICIT NONE

INCLUDE "IN_OUT_PATH_BSCAN.h"
INCLUDE "VARIABLES_BSCAN.h"
INCLUDE "READ_FILES_BSCAN.h"
INCLUDE "OPEN_WRITE_BSCAN.h"

!ERASE THE UNECESSARY NUMBER. 
!THE NUMBER MEANS THE VALUE OF THE J-1.
B_SCAN_IMAGE3(:,:,1) = 0

DO X = 1, DIS
   DO Y = 1, TRA
!CALCUATE THE BACKGROUND
      CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,2001,4000,BGR)

!REMOVE THE BACKGROUND
      B_SCAN_IMAGE4(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR
   END DO
END DO

!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
B_SCAN_IMAGE4(:,:,1) = 1
B_SCAN_IMAGE4(:,:,2) = 1

!G=1
!REMOVE MEAN IN THE EACH ROW
DO Z = 1, ROWS
!CALCULATE THE MEAN
    CALL remove_mean (B_SCAN_IMAGE4(:,1,Z),ROWS,DIS,MEAN)

!REMOVE THE MEAN 
!    PRINT *,G,"=", MEAN
    B_SCAN_IMAGE5(:,1,Z) = B_SCAN_IMAGE4(:,1,Z)- MEAN 
!G=G+1
END DO

!DIRECTION TEST
!ROWS
!B_SCAN_IMAGE5(:,1,1000:1100) = 10000000000000
!DISTANCE
!B_SCAN_IMAGE5(6000:7000,1,1000:1100) = 1000000000


INCLUDE "OUTPUT_A_SCOPE.h"
INCLUDE "OUTPUT_B_SCAN.h"

END PROGRAM
