PROGRAM CSCAN_MOGOD_GPR

USE MD_BACKGROUND
USE MD_FFT_IFFT
USE MD_FFT_HILBERT

IMPLICIT NONE

!USE GSSI_PROGRAM
INCLUDE "IN_OUT_PATH_CSCAN.h"

INCLUDE "VARIABLES_CSCAN.h"
INCLUDE "AUTO_READ_FILES_CSCAN.h"

!INCLUDE "VARIABLES2_250.h"
!INCLUDE "AUTO_READ_FILES_250.h"

INCLUDE "OPEN_WRITE_CSCAN.h"

DO X = 1, DIS
   DO Y = 1, TRA
!CALCULATE THE BACKGROUND
 CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,2001,4000,BGR)
 
!REMOVE THE BACKGROUND
     B_SCAN_IMAGE3(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR
   END DO 
END DO


!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
B_SCAN_IMAGE3(:,:,1) = 1
B_SCAN_IMAGE3(:,:,2) = 1


!HILBERT TRANSFORM
!HILBERT_A_SCOPE
DO X = 1, DIS
   DO Y = 1, TRA
      CALL fft_hilbert(B_SCAN_IMAGE3(X,Y,:),ROWS,HILBERT_SIGNAL) 
!     B_SCAN_IMAGE3(1,Y,:) = HILBERT_SIGNAL(1,1,:)
      HILBERT_B_SCAN(X,Y,:) = HILBERT_SIGNAL(1,1,:)
   END DO
END DO

INCLUDE "OUTPUT_A_B_C_SCOPE.h"
INCLUDE "OUTPUT_HILBERT.h"

END PROGRAM
