Program GSSI_PROGRAM
IMPLICIT NONE

INTEGER, PARAMETER ::  DISTANCE=1329
INTEGER, DIMENSION(4096,DISTANCE) :: B_SCAN_IMAGE
REAL, DIMENSION(4096,DISTANCE) :: IMAGE_AFTER_REMOVE_BG

CALL remove_background(B_SCAN_IMAGE,IMAGE_AFTER_REMOVE_BG)

END PROGRAM

!the name of subroutine must be small letter!
SUBROUTINE remove_background(B_SCAN_IMAGE, IMAGE_AFTER_REMOVE_BG) 
IMPLICIT NONE

INTEGER :: a
INTEGER, PARAMETER :: DISTANCE=1329
INTEGER, DIMENSION(4096,DISTANCE), INTENT(IN) :: B_SCAN_IMAGE
REAL, DIMENSION(4096) :: IMAGE_MEAN
REAL, DIMENSION(4096,DISTANCE), INTENT(OUT)  :: IMAGE_AFTER_REMOVE_BG

!ROWS=4096 


DO a=1, DISTANCE
  
  IMAGE_MEAN(a) = SUM(B_SCAN_IMAGE(a,:)) / SIZE(B_SCAN_IMAGE(a,:))
  IMAGE_AFTER_REMOVE_BG(a,:) = B_SCAN_IMAGE(a,:) - IMAGE_MEAN(a)
  
  PRINT*, IMAGE_MEAN(2)  
END DO
  
  

END SUBROUTINE

