PROGRAM HILBERT_GPR

USE MD_BACKGROUND
USE MD_STACKING
USE MD_FFT_IFFT
!USE MD_DFT_IDFT
USE MD_FFT_HILBERT
!USE MD_CROSS_CORRELATION
IMPLICIT NONE

INCLUDE "IN_OUT_PATH.h"
INCLUDE "VARIABLES.h"
!INCLUDE "AUTO_READ_FILES.h"
INCLUDE "AUTO_READ_FILES_2.h"
INCLUDE "OPEN_WRITE.h"

!======INITIALIZATION======
!===========================

!PRINT *, "PLEASE TYPE THE DISTANCE"
!READ *, DIS

!ERASE THE UNECESSARY NUMBER. 
!THE NUMBER MEANS THE VALUE OF THE J-1.
B_SCAN_IMAGE3(:,:,1) = 0

DO X = 1, DIS
   DO Y = 1, TRA
!CALCUATE THE BACKGROUND
      CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,2001,4000,BGR)

!REMOVE THE BACKGROUND
      B_SCAN_IMAGE4(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR
   END DO
END DO

!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
B_SCAN_IMAGE4(:,:,1) = 1
B_SCAN_IMAGE4(:,:,2) = 1

!STACKING THE A_SCOPE TO SUPPRESS THE BACKGROUND
DO Y = 1, TRA
   CALL stacking(B_SCAN_IMAGE4(:,Y,:),ROWS,DIS,STACKED_A_SCOPE)
   STACKED_B_SCAN(1,Y,:) = STACKED_A_SCOPE(1,1,:)
END DO

!FFT
imag = 0.0   

DO Y = 1, TRA
    CALL fft(STACKED_B_SCAN(1,Y,:), imag, ROWS, f_real(1,Y,:), f_imag(1,Y,:))
!    CALL ifft(f_real(1,Y,:), f_imag(1,Y,:), ROWS, ifft_real(1,Y,:), ifft_imag(1,Y,:))l
END DO

!DO Y = 1, TRA
!    CALL dft(STACKED_A_SCOPE(1,Y,:), imag, ROWS, dft_real(1,Y,:), dft_imag(1,Y,:))
!    CALL idft(dft_real(1,Y,:), dft_imag(1,Y,:), ROWS, idft_real(1,Y,:), idft_imag(1,Y,:)) 
!END DO


!HILBERT TRANSFORMATION
!FIRST SCAN
DO Y = 1, TRA
      CALL fft_hilbert(B_SCAN_IMAGE4(1,Y,:), ROWS, HILBERT_SIGNAL)
      HILBERT_B_SCAN(1,Y,:) = HILBERT_SIGNAL(1,1,:) 
END DO

!STACKED SCAN WITH THE AMOUNT OF THE DIS
DO Y = 1, TRA
      CALL fft_hilbert(STACKED_B_SCAN(1,Y,:), ROWS, HILBERT_STACKED_SIGNAL)
      HILBERT_STACKED_B_SCAN(1,Y,:) = HILBERT_STACKED_SIGNAL(1,1,:) 
END DO

!CROSS CORRELATION
!! crrl = 0.0 
!!    CALL cross_corl(B_SCAN_IMAGE4(1,1,:), &
!!                    B_SCAN_IMAGE4(1,1,:), ROWS,crrl)
    

!    CALL cross_corl(HILBERT_STACKED_SIGNAL(1,1,:), &
!                    HILBERT_STACKED_SIGNAL(1,1,:), ROWS,crrl)

INCLUDE "OUTPUT_A_SCOPE.h"
INCLUDE "OUTPUT_B_SCAN.h"
INCLUDE "OUTPUT_FFT_STACKED_A_SCOPE.h"
!INCLUDE "OUTPUT_DFT_STACKED_A_SCOPE.h"
INCLUDE "OUTPUT_HILBERT_A_SCOPE.h"
INCLUDE "OUTPUT_HILBERT_STACKED_A_SCOPE.h"
!INCLUDE "OUTPUT_CRRL.h"


END PROGRAM
