Program OPEN_GSSI

USE MD_BACKGROUND
USE MD_STACKING
USE MD_FFT_IFFT
!USE MD_DFT_IDFT
USE MD_FFT_HILBERT
IMPLICIT NONE

INCLUDE "IN_OUT_PATH.h"
INCLUDE "VARIABLES.h"
INCLUDE "PATH_NAME_OPEN.h"

!======INITIALIZATION=======
DIS = 0
!B_SCAN_IMAGE = 0
!B_SCAN_IMAGE2 = 0.0
!B_SCAN_IMAGE3 = 0.0
!INTENSITY = 0.0
!===========================

PRINT *, "PLEASE TYPE THE DISTANCE"
READ *, DIS

INCLUDE "ALLOCATE.h"

READ(10) HEADER,B_SCAN_IMAGE

!INTEGER => REAL*8
B_SCAN_IMAGE2=B_SCAN_IMAGE

!ERASE THE UNECESSARY NUMBER. 
!THE NUMBER MEANS THE VALUE OF THE J-1.
B_SCAN_IMAGE2(1,:) = 0


DO J = 1,DIS
!CALCUATE THE BACKGROUND
    CALL background(B_SCAN_IMAGE2(:,J),ROWS,2001,4000,BGR)

!REMOVE THE BACKGROUND
    B_SCAN_IMAGE3(:,J) = B_SCAN_IMAGE2(:,J) - BGR
END DO

!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
B_SCAN_IMAGE3(1,:) = 1
B_SCAN_IMAGE3(2,:) = 1

!STACKING THE A_SCOPE TO SUPPRESS THE BACKGROUND
    CALL stacking(B_SCAN_IMAGE3,ROWS,DIS,STACKED_A_SCOPE)

!FFT
imag = 0.0
    CALL fft(STACKED_A_SCOPE, imag, ROWS, f_real, f_imag)
    CALL ifft(f_real, f_imag, ROWS, ifft_real, ifft_imag)
!    CALL dft(STACKED_A_SCOPE, imag, ROWS, dft_real, dft_imag)
!    CALL idft(dft_real, dft_imag, ROWS, idft_real, idft_imag) 

!DO i = 1, ROWS
!       WRITE(*,*) i, ifft_real(i,1),ifft_imag(i,1), idft_real(i,1), idft_imag(i,1)
!END DO 


!HILBERT TRANSFORMATION
    CALL fft_hilbert(B_SCAN_IMAGE3(:,1),ROWS,HILBERT_SIGNAL)
    CALL fft_hilbert(STACKED_A_SCOPE,ROWS,HILBERT_STACKED_SIGNAL)

INCLUDE "OUTPUT_A_SCOPE.h"
INCLUDE "OUTPUT_B_SCAN.h"
INCLUDE "OUTPUT_STACKED_A_SCOPE.h"
INCLUDE "OUTPUT_FFT_STACKED_A_SCOPE.h"
INCLUDE "OUTPUT_DFT_STACKED_A_SCOPE.h"
INCLUDE "OUTPUT_HILBERT_A_SCOPE.h"
INCLUDE "OUTPUT_HILBERT_STACKED_A_SCOPE.h"

END PROGRAM
