!========PATH======================
CHARACTER (LEN=55) :: COMMON_PATH1
CHARACTER (LEN=55) :: COMMON_PATH2

CHARACTER (LEN=50) :: ITEM_NUMBER

CHARACTER (LEN=120) :: INPUT_PATH

CHARACTER (LEN=120) :: OUTPUT_PATH1
CHARACTER (LEN=120) :: OUTPUT_PATH2
CHARACTER (LEN=120) :: OUTPUT_PATH3
CHARACTER (LEN=120) :: OUTPUT_PATH4
CHARACTER (LEN=120) :: OUTPUT_PATH5
CHARACTER (LEN=120) :: OUTPUT_PATH6
CHARACTER (LEN=120) :: OUTPUT_PATH7
CHARACTER (LEN=120) :: OUTPUT_PATH8




CHARACTER (LEN=50) :: OUTPUT_NAME1
CHARACTER (LEN=50) :: OUTPUT_NAME2
CHARACTER (LEN=50) :: OUTPUT_NAME3
CHARACTER (LEN=50) :: OUTPUT_NAME4
CHARACTER (LEN=50) :: OUTPUT_NAME5
CHARACTER (LEN=50) :: OUTPUT_NAME6
CHARACTER (LEN=50) :: OUTPUT_NAME7
CHARACTER (LEN=50) :: OUTPUT_NAME8


!=================================


