
OPEN(UNIT=20, FILE=OUTPUT_PATH1, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE_GPR
OPEN(UNIT=21, FILE=OUTPUT_PATH2, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE_GPR_BGR
OPEN(UNIT=22, FILE=OUTPUT_PATH3, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE_GPR_MEAN
OPEN(UNIT=23, FILE=OUTPUT_PATH4, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_GPR_BGR
OPEN(UNIT=24, FILE=OUTPUT_PATH5, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_GPR_MEAN

