!=============================PATH===================================
!COMMON_PATH1="/home/changwan/GPR/2020_11(three tombs)/201109.PRJ/"
!COMMON_PATH1="/home/changwan/GPR/201223/"
!COMMON_PATH1="/home/changwan/GPR/GPR_202107/210713.PRJ/"
!COMMON_PATH1="/home/changwan/GPR/GPR_202107/"

!COMMON_PATH1="/home/changwan/GPR/"
!COMMON_PATH1="/home/changwan/GPR/"

!COMMON_PATH2="/home/changwan/GPR/GPR_202107/"


!COMMON_PATH1="/home/changwan/GPR/GPR_202107/210722.PRJ/"
!COMMON_PATH2="/home/changwan/GPR/GPR_202107/210722.PRJ/"

COMMON_PATH1="/mnt/l/GPR_DATA/"
COMMON_PATH2="/mnt/l/GPR_DATA/"



!ITEM_NUMBER="210722__005.DZT"
!ITEM_NUMBER="210722__004.DZT"
!ITEM_NUMBER="210722__005.DZT"
!ITEM_NUMBER="210722__002.DZT"

ITEM_NUMBER="210722__003.DZT"


!ITEM_NUMBER="Source_sine.txt"

OUTPUT_NAME1="A_SCOPE_GPR.txt"
OUTPUT_NAME2="A_SCOPE_GPR_BGR.txt"
OUTPUT_NAME3="B_SCAN_IMAGE_GPR.txt"
OUTPUT_NAME4="STACKED_A_SCOPE.txt"
OUTPUT_NAME5="FFT_STACKED_A_GPR.txt"
OUTPUT_NAME6="HILBERT_A_GPR.txt"
OUTPUT_NAME7="HILBERT_STACKED_A_GPR.txt"
OUTPUT_NAME8="DFT_STACKED_A_GPR.txt"


!OUTPUT_NAME1=ITEM_NUMBER//"A_SCOPE_GPR.txt"
!OUTPUT_NAME2=ITEM_NUMBER//"A_SCOPE_GPR_BGR.txt"
!OUTPUT_NAME3=ITEM_NUMBER//"B_SCAN_IMAGE_GPR.txt"
!OUTPUT_NAME4=ITEM_NUMBER//"STACKED_A_SCOPE.txt"
!OUTPUT_NAME5=ITEM_NUMBER//"FFT_STACKED_A_GPR.txt"
!OUTPUT_NAME6=ITEM_NUMBER//"HILBERT_A_GPR.txt"
!OUTPUT_NAME7=ITEM_NUMBER//"HILBERT_STACKED_A_GPR.txt"
!OUTPUT_NAME8=ITEM_NUMBER//"DFT_STACKED_A_GPR.txt"



INPUT_PATH = TRIM(COMMON_PATH1)//ITEM_NUMBER
OUTPUT_PATH1 = TRIM(COMMON_PATH2)//OUTPUT_NAME1
OUTPUT_PATH2 = TRIM(COMMON_PATH2)//OUTPUT_NAME2
OUTPUT_PATH3 = TRIM(COMMON_PATH2)//OUTPUT_NAME3
OUTPUT_PATH4 = TRIM(COMMON_PATH2)//OUTPUT_NAME4
OUTPUT_PATH5 = TRIM(COMMON_PATH2)//OUTPUT_NAME5
OUTPUT_PATH6 = TRIM(COMMON_PATH2)//OUTPUT_NAME6
OUTPUT_PATH7 = TRIM(COMMON_PATH2)//OUTPUT_NAME7
OUTPUT_PATH8 = TRIM(COMMON_PATH2)//OUTPUT_NAME8



!=====================================================================


OPEN(UNIT=10, FILE=INPUT_PATH, FORM='UNFORMATTED', ACCESS='STREAM', STATUS='OLD', ACTION='READ')
!OPEN(UNIT=10, FILE=INPUT_PATH, FORM='FORMATTED', STATUS='OLD', ACTION='READ')


OPEN(UNIT=20,FILE=OUTPUT_PATH1,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=21,FILE=OUTPUT_PATH2,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=22,FILE=OUTPUT_PATH3,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=23,FILE=OUTPUT_PATH4,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=24,FILE=OUTPUT_PATH5,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=25,FILE=OUTPUT_PATH6,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=26,FILE=OUTPUT_PATH7,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=27,FILE=OUTPUT_PATH8,STATUS='REPLACE',ACTION='WRITE')






