

ITEM_NUMBER=TRIM(FH1//FT)

!=============================PATH===================================
COMMON_PATH1="/home/changwan/GPR/211027_3/"
COMMON_PATH2="/home/changwan/GPR/211027_3/"

!COMMON_PATH1="/home/changwan/GPR/211027_4/"
!COMMON_PATH2="/home/changwan/GPR/211027_4/"

!COMMON_PATH1="/mnt/l/MOGOD_GPR/2021/F1/250MHz/"
!COMMON_PATH1="/mnt/l/MOGOD_GPR/2021/F1/500MHz/"
!COMMON_PATH2="/mnt/l/MOGOD_GPR/2021/"


OUTPUT_NAME1="A_SCOPE_GPR.txt"
OUTPUT_NAME2="A_SCOPE_GPR_BGR.txt"
OUTPUT_NAME3="A_SCOPE_GPR_MEAN.txt"
OUTPUT_NAME4="B_SCAN_GPR_BGR.txt"
OUTPUT_NAME5="B_SCAN_GPR_MEAN.txt"


INPUT_PATH = TRIM(COMMON_PATH1)//ITEM_NUMBER
OUTPUT_PATH1 = TRIM(COMMON_PATH2)//OUTPUT_NAME1
OUTPUT_PATH2 = TRIM(COMMON_PATH2)//OUTPUT_NAME2
OUTPUT_PATH3 = TRIM(COMMON_PATH2)//OUTPUT_NAME3
OUTPUT_PATH4 = TRIM(COMMON_PATH2)//OUTPUT_NAME4
OUTPUT_PATH5 = TRIM(COMMON_PATH2)//OUTPUT_NAME5
!=====================================================================

!PRINT*, INPUT_PATH

OPEN(UNIT=10, FILE=INPUT_PATH,   ACCESS='STREAM',  STATUS='OLD', ACTION='READ')

!======INITIALIZATION=======
!B_SCAN_IMAGE = 0
!B_SCAN_IMAGE2 = 0
!===========================  

Y=TRA

      READ(10) HEADER, B_SCAN_IMAGE(:,:,Y)
             
      B_SCAN_IMAGE2(:,:,Y) = B_SCAN_IMAGE(:,:,Y)

!DIRECTION CHECK
!B_SCAN_IMAGE(1000:1100,6000:7000,1) = 1000000



!+++++REVERSING THE EVEN_GPR TRACKS+++++++++++++++++++++++
!!     IF (MOD(Y,2)/=0) THEN
!!         B_SCAN_IMAGE2(:,:,Y) = B_SCAN_IMAGE(:,:,Y)
!!     ELSE
!!      DO P=1,DIS
!!          B_SCAN_IMAGE2(:,(DIS-P+1),Y) = B_SCAN_IMAGE(:,P,Y) 
!!      END DO
!!     END IF

!+++++SIMPLELY FLIP THE GPR TRACK+++++
!        DO P=1,DIS
!          B_SCAN_IMAGE2(:,(DIS-P+1),Y) = B_SCAN_IMAGE(:,P,Y) 
!        END DO
 
      PRINT *, "Y=",Y    


DO X = 1, DIS
  DO Y = 1, TRA
    DO Z = 1, ROWS

      B_SCAN_IMAGE3(X,Y,Z) = B_SCAN_IMAGE2(Z,X,Y)

!      PRINT *, X,Y,Z,"<----",Z,X,Y

    END DO
  END DO
END DO
 



