PROGRAM CSCAN_GPR_EW

USE MD_BASIC

IMPLICIT NONE

INCLUDE "IN_OUT_PATH_CSCAN_reader.h"
INCLUDE "VARIABLES_CSCAN_EW_reader.h"
INCLUDE "AUTO_READ_FILES_CSCAN_reader.h"
INCLUDE "OPEN_WRITE_CSCAN_reader.h"


!REMOVE THE BACKGROUND
DO X = 0, DIS-1
DO Y = 0, TRA-1

   CALL background(B_SCAN_IMAGE3(X,Y,:), ROWS, 501, 600, BGR)
   B_SCAN_IMAGE4(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR

END DO 
END DO 

!PRINT*, "RCD=",ROW_COR_DIS
!DO Y = 1, TRA2
!   ROW_COR_PIXEL(Y) = INT(ROW_COR_DIS(Y)/0.05)  !5 cm = 0.05 m
!END DO 
!PRINT*, "RCP=", ROW_COR_PIXEL

!CHANGE ORDER OF THE LINES.
!ROW_COR_PIXEL2 = ROW_COR_PIXEL

!INCLUDE "MIHO12_H_edit.h"
!INCLUDE "MIHO21_H_edit.h"
!INCLUDE "MIHO21_H_edit.h"
!INCLUDE "MIHO30_H_edit.h"

!DO Y  = 1, TRA2
!   B_SCAN_IMAGE5(:, 10 * (Y-1), :) = B_SCAN_IMAGE4_CO(:, (Y-1), :)
!END DO 

!ZERO_PADDING
INCLUDE "ZERO_PADDING.h"
INCLUDE "OUTPUT_A_SCAN_reader.h"        !20
!INCLUDE "OUTPUT_B_SCAN_reader.h"        !30 
!INCLUDE "OUTPUT_C_SCAN_reader.h"        !40
INCLUDE "OUTPUT_3DCUBE_reader.h"         !5

!INCLUDE "OUTPUT_GNSS.h"                !50


END PROGRAM
