

DO CO = 1, 22
       ROW_COR_PIXEL2(CO) = ROW_COR_PIXEL(23-CO)
END DO 


!PRINT*, "RCP=", ROW_COR_PIXEL2

DO Y = 1, TRA2
PRINT*, Y, "RCP=", ROW_COR_PIXEL(Y), ROW_COR_PIXEL2(Y)

DO X = 0, DIS-ROW_COR_PIXEL2(Y)
   B_SCAN_IMAGE4(X+ROW_COR_PIXEL2(Y),Y-1,:) = B_SCAN_IMAGE3(X,Y-1,:)

END DO 
END DO 

!CHANGE ORDER OF THE LINES.
B_SCAN_IMAGE4_CO= B_SCAN_IMAGE4

DO CO2 = 0, 21        
        B_SCAN_IMAGE4_CO(:,CO2,:) = B_SCAN_IMAGE4(:,21-CO2,:) 
END DO 


