
ROW_COR_PIXEL2(1) = ROW_COR_PIXEL(5)
ROW_COR_PIXEL2(2) = ROW_COR_PIXEL(4)
ROW_COR_PIXEL2(3) = ROW_COR_PIXEL(3)
ROW_COR_PIXEL2(4) = ROW_COR_PIXEL(2)
ROW_COR_PIXEL2(5) = ROW_COR_PIXEL(1)

!PRINT*, "RCP=", ROW_COR_PIXEL2

DO Y = 1, TRA2
PRINT*, Y, "RCP=", ROW_COR_PIXEL(Y), ROW_COR_PIXEL2(Y)

DO X = 0, DIS-ROW_COR_PIXEL2(Y)
   B_SCAN_IMAGE4(X+ROW_COR_PIXEL2(Y),Y-1,:) = B_SCAN_IMAGE3(X,Y-1,:)

END DO 
END DO 

!CHANGE ORDER OF THE LINES.
B_SCAN_IMAGE4_CO= B_SCAN_IMAGE4

B_SCAN_IMAGE4_CO(:,0,:) = B_SCAN_IMAGE4(:,4,:) 
B_SCAN_IMAGE4_CO(:,1,:) = B_SCAN_IMAGE4(:,3,:) 
B_SCAN_IMAGE4_CO(:,2,:) = B_SCAN_IMAGE4(:,2,:) 
B_SCAN_IMAGE4_CO(:,3,:) = B_SCAN_IMAGE4(:,1,:) 
B_SCAN_IMAGE4_CO(:,4,:) = B_SCAN_IMAGE4(:,0,:) 


