
OPEN(UNIT=20, FILE=OUTPUT_PATH20, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
!OPEN(UNIT=21, FILE=OUTPUT_PATH21, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
!OPEN(UNIT=22, FILE=OUTPUT_PATH22, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
OPEN(UNIT=23, FILE=OUTPUT_PATH23, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE

OPEN(UNIT=30, FILE=OUTPUT_PATH30, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
!OPEN(UNIT=31, FILE=OUTPUT_PATH31, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=32, FILE=OUTPUT_PATH32, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
!OPEN(UNIT=39, FILE=OUTPUT_PATH39, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE


OPEN(UNIT=40, FILE=OUTPUT_PATH40, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE
!OPEN(UNIT=41, FILE=OUTPUT_PATH41, ACCESS='STREAM',STATUS='REPLACE', ACTION='WRITE') !3D_CUBE_IMAGE  

!OPEN(UNIT=41, FILE=OUTPUT_PATH41, STATUS='REPLACE', ACTION='WRITE')   !C_SCAN

OPEN(UNIT=42, FILE=OUTPUT_PATH42, STATUS='REPLACE', ACTION='WRITE')   !C_SCAN
OPEN(UNIT=43, FILE=OUTPUT_PATH43, ACCESS='STREAM', STATUS='REPLACE', ACTION='WRITE')   !C_SCAN


!OPEN(UNIT=40, FILE=OUTPUT_PATH40, ACCESS='STREAM', STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE


!OPEN(UNIT=50, FILE=OUTPUT_PATH50, STATUS='REPLACE', ACTION='WRITE')   !CRRL


!OPEN(UNIT=80, FILE=OUTPUT_PATH80, STATUS='REPLACE', ACTION='WRITE')   !HORIZON PICK




