!========PATH======================
CHARACTER (LEN=70) :: COMMON_PATH1
CHARACTER (LEN=55) :: COMMON_PATH2

CHARACTER (LEN=120) :: INPUT_PATH

CHARACTER (LEN=120) :: OUTPUT_PATH20
CHARACTER (LEN=120) :: OUTPUT_PATH30
CHARACTER (LEN=120) :: OUTPUT_PATH31
CHARACTER (LEN=120) :: OUTPUT_PATH40
CHARACTER (LEN=120) :: OUTPUT_PATH50


CHARACTER (LEN=50) :: INPUT_NAME10
CHARACTER (LEN=50) :: OUTPUT_NAME20
CHARACTER (LEN=50) :: OUTPUT_NAME30
CHARACTER (LEN=50) :: OUTPUT_NAME31
CHARACTER (LEN=50) :: OUTPUT_NAME40
CHARACTER (LEN=50) :: OUTPUT_NAME50
!=================================


