
OPEN(UNIT=20, FILE=OUTPUT_PATH20, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
OPEN(UNIT=30, FILE=OUTPUT_PATH30, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=31, FILE=OUTPUT_PATH31, STATUS='REPLACE', ACTION='WRITE')   !C_SCAN_IMAGE
OPEN(UNIT=40, FILE=OUTPUT_PATH40, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE
OPEN(UNIT=50, FILE=OUTPUT_PATH50, STATUS='REPLACE', ACTION='WRITE')   !HILBERT_3D_CUBE_IMAGE



