PROGRAM CSCAN_POL_powerdB

USE MD_BASIC

IMPLICIT NONE

CHARACTER (LEN=140) :: PATH
CHARACTER (LEN=140) :: PATH2
CHARACTER (LEN=140) :: PATH3


CHARACTER (LEN=40) :: INPUT_NAME
CHARACTER (LEN=40) :: INPUT_NAME2

CHARACTER (LEN=140) :: INPUT_PATH
CHARACTER (LEN=140) :: INPUT_PATH2

CHARACTER (LEN=40) :: OUTPUT_NAME
CHARACTER (LEN=140) :: OUTPUT_PATH


INTEGER :: X, Z, F, Y
INTEGER, PARAMETER :: TRA = 18
INTEGER, PARAMETER :: DIS = 41
INTEGER, PARAMETER :: ROWS = 4096


REAL*8, DIMENSION(ROWS,TRA,DIS) ::  POWER_dB
REAL*8, DIMENSION(ROWS,TRA,DIS) ::  POWER_dB2

REAL*8, DIMENSION(DIS,TRA,ROWS) ::  POWER_dB3
REAL*8, DIMENSION(DIS,TRA,ROWS) ::  POWER_dB4
REAL*8, DIMENSION(DIS,TRA,ROWS) ::  POWER_dB5

!Miho_ri
!PATH ="/home/changwan/GPR_DATA/KOREA/MIHO_ri/3D_trench/40MHz/BSCAN/EW/attribute/"
!PATH2="/home/changwan/GPR_DATA/KOREA/MIHO_ri/3D_trench/40MHz/BSCAN/NS/attribute/"
!PATH3 = "/home/changwan/GPR_DATA/KOREA/MIHO_ri/3D_trench/40MHz/BSCAN/"


PATH ="/home/changwan/GPR_DATA/KOREA/MIHO_ri/40MHz/2023/EW/attribute/"
PATH2 ="/home/changwan/GPR_DATA/KOREA/MIHO_ri/40MHz/2023/NS/attribute/"

PATH3 = "/home/changwan/GPR_DATA/KOREA/MIHO_ri/40MHz/2023/POL/"


INPUT_NAME = "3D_HILBERT_powerdB.txt"
INPUT_NAME2 ="3D_HILBERT_powerdB.txt"

INPUT_PATH = TRIM(PATH)//INPUT_NAME
INPUT_PATH2 = TRIM(PATH2)//INPUT_NAME2

OUTPUT_NAME = "CSCAN_POL_diff_powerdB.txt"
OUTPUT_PATH = TRIM(PATH3)//OUTPUT_NAME

PRINT *, INPUT_PATH
PRINT *, INPUT_PATH2
PRINT *, OUTPUT_PATH

OPEN(11, FILE=INPUT_PATH, FORM="FORMATTED", STATUS="OLD", ACTION="READ")
OPEN(12, FILE=INPUT_PATH2, FORM="FORMATTED", STATUS="OLD", ACTION="READ")
OPEN(21, FILE=OUTPUT_PATH, FORM="FORMATTED", STATUS="REPLACE", ACTION="WRITE")


!EW
READ(11,*) POWER_dB
DO X = 1, DIS
DO Y = 1, TRA 
DO Z = 1, ROWS
      POWER_dB3(X,Y,Z) = POWER_dB(Z,Y,X)

!      PRINT *, X,Y,Z,"<----",Z,X,Y
END DO
END DO
END DO

!DO X = 1, TRA 
!DO Y = 1, LINE
!DO Z = 1, ROWS
!      POWER_dB3_2(X,Y,Z) = POWER_dB3(Y,X,Z)

!      PRINT *, X,Y,Z,"<----",Y,X,Z
    
!END DO
!END DO
!END DO

PRINT *, "COMPLETED TO READ A EW FILE"    

!NS
READ(12,*) POWER_dB2
DO X = 1, DIS
DO Y = 1, TRA 
DO Z = 1, ROWS 

       POWER_dB4(X,Y,Z) = POWER_dB2(Z,Y,X)

!      PRINT *, X,Y,Z,"<----",Z,X,Y
    
END DO
END DO
END DO

!DO X = 1, TRA 
!DO Y = 1, LINE
!DO Z = 1, ROWS

!      POWER_dB4_2(X,Y,Z) = POWER_dB4(Y,X,Z)

!      PRINT *, X,Y,Z,"<----",Y,X,Z
    
!END DO
!END DO
!END DO

PRINT *, "COMPLETED TO READ A NS FILE"    

DO X = 1, DIS
DO Y = 1, TRA
DO Z = 1, ROWS
   POWER_dB5(X,Y,Z) = POWER_dB4(X,Y,Z) - POWER_dB3(X,Y,Z)
END DO 
END DO
END DO 

DO X = 1, DIS
DO Y = 1, TRA
   WRITE(21,*) (POWER_dB3(X,Y,Z), Z = 1, ROWS)


END DO 
END DO 

!THIS STRUCTURE (F X Y) X Z CAN BE PRINTED.
!(F X Y) IS THE C_SCAN.

END PROGRAM
