PROGRAM CSCAN_POL_powerdB
IMPLICIT NONE

CHARACTER (LEN=140) :: PATH
CHARACTER (LEN=140) :: PATH2
CHARACTER (LEN=140) :: PATH3


CHARACTER (LEN=40) :: INPUT_NAME
CHARACTER (LEN=40) :: INPUT_NAME2

CHARACTER (LEN=140) :: INPUT_PATH
CHARACTER (LEN=140) :: INPUT_PATH2

CHARACTER (LEN=40) :: OUTPUT_NAME
CHARACTER (LEN=140) :: OUTPUT_PATH


INTEGER :: X, Z, F, Y
INTEGER, PARAMETER :: LINE = 17
INTEGER, PARAMETER :: TRA = 41
INTEGER, PARAMETER :: ROWS = 4096

REAL*8, DIMENSION(LINE,TRA,ROWS) ::  POWER_dB
REAL*8, DIMENSION(LINE,TRA,ROWS) ::  POWER_dB2
REAL*8, DIMENSION(LINE,TRA,ROWS) ::  POWER_dB3


PATH ="/home/changwan/GPR_DATA/KOREA/MIHO_ri/40MHz/CSCAN3/EW/"
PATH2="/home/changwan/GPR_DATA/KOREA/MIHO_ri/40MHz/CSCAN3/NS/"
PATH3 = "/home/changwan/GPR_DATA/KOREA/MIHO_ri/40MHz/CSCAN3/"

INPUT_NAME = "HILBERT_3DCUBE_stacking_powerdB.txt"
INPUT_NAME2 = "HILBERT_3DCUBE_stacking_powerdB.txt"

INPUT_PATH = TRIM(PATH)//INPUT_NAME
INPUT_PATH2 = TRIM(PATH2)//INPUT_NAME2


OUTPUT_NAME = "CSCAN_POL_GPR_powerdB.txt"
OUTPUT_PATH = TRIM(PATH3)//OUTPUT_NAME

PRINT *, INPUT_PATH
PRINT *, INPUT_PATH2
PRINT *, OUTPUT_PATH

OPEN(11, FILE=INPUT_PATH, FORM="FORMATTED", STATUS="OLD", ACTION="READ")
OPEN(12, FILE=INPUT_PATH2, FORM="FORMATTED", STATUS="OLD", ACTION="READ")
OPEN(21, FILE=OUTPUT_PATH, FORM="FORMATTED", STATUS="REPLACE", ACTION="WRITE")



READ(11,*) POWER_dB
READ(12,*) POWER_dB2

POWER_dB3 = POWER_dB2 - POWER_dB


DO F = 1, LINE
DO Y = 1, TRA
    WRITE(21,*) (POWER_dB3(F,Y,Z), Z = 1, ROWS)
END DO 
END DO 

!THIS STRUCTURE (F X Y) X Z CAN BE PRINTED.
!(F X Y) IS THE C_SCAN.

END PROGRAM
