PROGRAM TW4FILTER
IMPLICIT NONE

CHARACTER(LEN=255) :: PATH
CHARACTER(LEN=255) :: INPUT_PATH
CHARACTER(LEN=255) :: OUTPUT_PATH

CHARACTER(LEN=255) :: IFN                   !INPUT-FILE NAME
CHARACTER(LEN=255) :: OFN                   !OUTPUT-FILE NAME

CHARACTER(LEN=20) :: FMT,FMT2

INTEGER, PARAMETER :: ROWS = 512
!INTEGER, PARAMETER 

INTEGER :: I, X, BS, BE, BAND
REAL :: T  
REAL*8 :: pi = Acos(-1.0)
REAL*8 :: THETA_1, THETA_2

!REAL*8, DIMENSION(ROWS,5) :: FFT
REAL*8, DIMENSION(5,ROWS) :: FFT
REAL*8, DIMENSION(1,ROWS) :: TW            !TIME WINDOW
REAL*8, DIMENSION(3,ROWS) :: TW_FFT

PATH = "/home/changwan/GPR_DATA/MOGOD/2022/Site-1/250"
 
IFN = "/FFT.txt"
OFN = "/TW_FFT.txt"

INPUT_PATH = TRIM(PATH)//IFN
PRINT *, INPUT_PATH
OUTPUT_PATH = TRIM(PATH)//OFN
PRINT *, OUTPUT_PATH

OPEN(UNIT=10, FILE=INPUT_PATH, FORM='FORMATTED', STATUS='OLD', ACTION='READ')
OPEN(UNIT=20, FILE=OUTPUT_PATH, FORM='FORMATTED', STATUS='REPLACE', ACTION='WRITE')

!FMT = "(5F20.10)"

!READ(10,FMT) FFT
READ(10,*) FFT


!==========HIGH-PASS FILTER===========
BAND = 6
BS = BAND   !BAND START
BE = (ROWS-BAND)+1   !BAND END
T = 1

DO X = 1, BS
    TW(1,X) = EXP(-((X-6*T)/3*T)**2)
END DO


DO X = BS+1, ROWS-BAND
    TW(1,X) = 1.0
END DO

DO X = BE, ROWS
     TW(1,X) = EXP(-(((ROWS-X)-6*T)/3*T)**2)
END DO

!=====================================


DO X = 1, BS
   TW_FFT(1,X) =  TW(1,X) * FFT(1,BAND+1)
   TW_FFT(2,X) =  TW(1,X) * FFT(2,BAND+1)
   TW_FFT(3,X) =  TW(1,X) * FFT(3,BAND+1)
END DO 

DO X = BS+1,ROWS-BAND
   TW_FFT(1,X) =  TW(1,X) * FFT(1,X)
   TW_FFT(2,X) =  TW(1,X) * FFT(2,X)
   TW_FFT(3,X) =  TW(1,X) * FFT(3,X)
END DO 

DO X = BE,ROWS
   TW_FFT(1,X) =  TW(1,X) * FFT(1,ROWS-BAND+1)
   TW_FFT(2,X) =  TW(1,X) * FFT(2,ROWS-BAND+1)
   TW_FFT(3,X) =  TW(1,X) * FFT(3,ROWS-BAND+1)
END DO 


DO X = 1, ROWS
   WRITE(20,*) TW(1,X),&
            TW_FFT(1,X),FFT(1,X),&
            TW_FFT(2,X),FFT(2,X),&
            TW_FFT(3,X),FFT(3,X)
END DO

END PROGRAM TW4FILTER

