OPEN(UNIT=20,FILE=OUTPUT_PATH20,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=21,FILE=OUTPUT_PATH21,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=22,FILE=OUTPUT_PATH22,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=23,FILE=OUTPUT_PATH22,STATUS='REPLACE',ACTION='WRITE')



OPEN(UNIT=30,FILE=OUTPUT_PATH30,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=31,FILE=OUTPUT_PATH31,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=32,FILE=OUTPUT_PATH32,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=33,FILE=OUTPUT_PATH33,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=34,FILE=OUTPUT_PATH34,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=35,FILE=OUTPUT_PATH35,STATUS='REPLACE',ACTION='WRITE')
