PROGRAM BSCAN_GPR

USE MD_BACKGROUND
USE MD_STACKING
USE MD_MEAN_ASCAN
USE MD_MVMEAN

USE MD_FFT_IFFT
USE MD_DFT_IDFT

USE MD_FFT_HILBERT
USE MD_DFT_HILBERT

!USE MD_CROSS_CORRELATION

IMPLICIT NONE

INCLUDE "IN_OUT_PATH.h"
INCLUDE "VARIABLES_BSCAN.h"
INCLUDE "READ_FILES_BSCAN.h"
INCLUDE "OPEN_WRITE.h"

!======INITIALIZATION======
!===========================
!ERASE THE UNECESSARY NUMBER. 
!THE NUMBER MEANS THE VALUE OF THE J-1.
B_SCAN_IMAGE3(:,:,1) = 0.0

DO X = 1, DIS
!CALCUATE THE BACKGROUND
!      CALL background(B_SCAN_IMAGE3(X,1,:),ROWS,2001,4000,BGR) !KOERA
!      CALL background(B_SCAN_IMAGE3(X,1,:),ROWS,491,500,BGR)  !MOGOD
      CALL background(B_SCAN_IMAGE3(X,1,:),ROWS,501,600,BGR)  !MOGOD

!REMOVE THE BACKGROUND
      B_SCAN_IMAGE4(X,1,:) = B_SCAN_IMAGE3(X,1,:) - BGR
END DO

!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
!B_SCAN_IMAGE4(:,:,1) = 1
!B_SCAN_IMAGE4(:,:,2) = 1


!REMOVE MEAN_ASCAN 
!!   CALL mean_ascanx(B_SCAN_IMAGE4(:,1,:), DIS, ROWS, MEAN_A_SCOPE) 
!!DO X = 1, DIS
!!   DO Z = 1, ROWS
!!  B_SCAN_IMAGE5(X, 1, Z) = B_SCAN_IMAGE4(X, 1, Z) - MEAN_A_SCOPE(1,1,Z)
!!   END DO 
!!END DO


!FFT
!!imag = 0.0   

!!DO X = 1, DIS
!!    CALL fft(B_SCAN_IMAGE4(X,1,:), imag, ROWS, f_real(1,Y,:), f_imag(1,Y,:))
!    CALL ifft(f_real(1,Y,:), f_imag(1,Y,:), ROWS, ifft_real(1,Y,:), ifft_imag(1,Y,:))l
!!END DO

!DO Y = 1, TRA
!    CALL dft(STACKED_A_SCOPE(1,Y,:), imag, ROWS, dft_real(1,Y,:), dft_imag(1,Y,:))
!    CALL idft(dft_real(1,Y,:), dft_imag(1,Y,:), ROWS, idft_real(1,Y,:), idft_imag(1,Y,:)) 
!END DO


!HILBERT TRANSFORMATION
!FIRST SCAN
!!DO Y = 1, TRA
!!      CALL fft_hilbert(B_SCAN_IMAGE4(1,Y,:), ROWS, HILBERT_SIGNAL)
 !!     HILBERT_B_SCAN(1,Y,:) = HILBERT_SIGNAL(1,1,:) 
!!END DO

!STACKED SCAN WITH THE AMOUNT OF THE DIS
DO X = 1, DIS
      CALL fft_hilbert(B_SCAN_IMAGE4(X,1,:), ROWS, HILBERT_SIGNAL)
!       CALL dft_hilbert(B_SCAN_IMAGE5(X,1,:), ROWS, HILBERT_SIGNAL)
      HILBERT_B_SCAN(X,1,:) = HILBERT_SIGNAL(1,1,:) 

END DO


!GAIN CONTROL BASED ON INSTANTENOUS POWER
DO X = 1, DIS
DO Z = 1, ROWS
   HILBERT_power(X,1,Z) = SQRT(HILBERT_B_SCAN(X,1,Z)**2 + B_SCAN_IMAGE4(X,1,Z)**2)
END DO
END DO  
  
  CALL mv_meany( HILBERT_power, MV_WIN, DIS, ROWS, ROWS2, HILBERT_power2) 
  PRINT *, "MV_WIN=",MV_WIN 


!CROSS CORRELATION
!! crrl = 0.0 
!!    CALL cross_corl(B_SCAN_IMAGE4(1,1,:), &
!!                    B_SCAN_IMAGE4(1,1,:), ROWS,crrl)   

!    CALL cross_corl(HILBERT_STACKED_SIGNAL(1,1,:), &
!                    HILBERT_STACKED_SIGNAL(1,1,:), ROWS,crrl)

INCLUDE "OUTPUT_A_SCAN.h"                   !20,21,22,23
INCLUDE "OUTPUT_B_SCAN.h"                   !30,31,32,33 
INCLUDE "OUTPUT_HILBERT.h"                  !50,51
INCLUDE "OUTPUT_PHASE.h"                    !60,61

END PROGRAM
