PROGRAM CSCAN_GPR_NS

USE MD_BASIC
USE MD_FFT_IFFT
USE MD_FFT_HILBERT

USE MD_INTERPRE

IMPLICIT NONE

!USE GSSI_PROGRAM
INCLUDE "IN_OUT_PATH_CSCAN.h"
INCLUDE "VARIABLES_CSCAN_SUM.h"
INCLUDE "READ_FILES_CSCAN_SUM.h"
INCLUDE "OPEN_WRITE_CSCAN.h"

!POWER SUM
DO X  = 1, DIS
DO Y  = 1, TRA 
      POWER_SUM(X,Y,:) = (B_SCAN_IMAGE6F(X,Y,:) + B_SCAN_IMAGE8(X,Y,:)) /2.0
END DO 
END DO 

!AMPLITUDE SUM
DO X  = 1, DIS
DO Y  = 1, TRA 
      AMP_SUM(X,Y,:) = (B_SCAN_IMAGE7F(X,Y,:) + B_SCAN_IMAGE9(X,Y,:)) /2.0

END DO 
END DO 


!HILBERT TRANSFORM
!HILBERT_A_SCOPE
DO X = 1, DIS 
DO Y = 1, TRA
      CALL fft_hilbert(AMP_SUM(X,Y,:),ROWS,HILBERT_SIGNAL) 
      HILBERT_AMP_SUM(X,Y,:) = HILBERT_SIGNAL(1,1,:)
END DO
END DO



YY = 17


PRINT*,  "COMPLETED TO PICK HOROZIN_1"
PRINT*, "WRITE OUT THE RESULTS"
PRINT*, "WAITING..."


INCLUDE "OUTPUT_A_SCAN.h"               !20
INCLUDE "OUTPUT_B_SCAN.h"               !60, 61  POWERSUM, AMPLITUE_SUM
!INCLUDE "OUTPUT_C_SCAN.h"              !40
INCLUDE "OUTPUT_AMPSUM.h"               !70      AMPSUM POWER
INCLUDE "OUTPUT_MSR_H.h"                !90, 91
INCLUDE "OUTPUT_PH.h"                   !92     POWER SUM HORISON
INCLUDE "OUTPUT_AH.h"                   !93     AMPSUM POWER HORISON



END PROGRAM
