PROGRAM CSCAN_MOGOD_GPR

IMPLICIT NONE

!USE GSSI_PROGRAM
INCLUDE "IN_OUT_PATH_CSCAN.h"
INCLUDE "VARIABLES_CSCAN.h"
INCLUDE "READ_FILES_CSCAN.h"
INCLUDE "OPEN_WRITE_CSCAN.h"


!INCLUDE "OUTPUT_A_SCAN.h"  !20
!INCLUDE "OUTPUT_B_SCAN.h"  !30
!INCLUDE "OUTPUT_C_SCAN.h"  !40
INCLUDE "OUTPUT_MVMEAN.h"  !50


END PROGRAM
