
!OPEN(UNIT=20, FILE=OUTPUT_PATH20, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
!OPEN(UNIT=21, FILE=OUTPUT_PATH21, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE


!OPEN(UNIT=30, FILE=OUTPUT_PATH30, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=31, FILE=OUTPUT_PATH31, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE

!OPEN(UNIT=40, FILE=OUTPUT_PATH40, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE
!OPEN(UNIT=40, FILE=OUTPUT_PATH40, ACCESS='STREAM', STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE
OPEN(UNIT=41, FILE=OUTPUT_PATH41, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE


OPEN(UNIT=50, FILE=OUTPUT_PATH50, STATUS='REPLACE', ACTION='WRITE')   !FFT
OPEN(UNIT=51, FILE=OUTPUT_PATH51, STATUS='REPLACE', ACTION='WRITE')   !FFT


OPEN(UNIT=60, FILE=OUTPUT_PATH60, STATUS='REPLACE', ACTION='WRITE')   !HILBERT
OPEN(UNIT=70, FILE=OUTPUT_PATH70, STATUS='REPLACE', ACTION='WRITE')   !PHASE

OPEN(UNIT=80, FILE=OUTPUT_PATH80, STATUS='REPLACE', ACTION='WRITE')   !BAND-PASS FILTER
OPEN(UNIT=81, FILE=OUTPUT_PATH81, STATUS='REPLACE', ACTION='WRITE')   !BAND-PASS FILTER
OPEN(UNIT=82, FILE=OUTPUT_PATH82, STATUS='REPLACE', ACTION='WRITE')   !BAND-PASS FILTER


OPEN(UNIT=85, FILE=OUTPUT_PATH85, STATUS='REPLACE', ACTION='WRITE')   !HIGH-PASS FILTER
!OPEN(UNIT=86, FILE=OUTPUT_PATH86, STATUS='REPLACE', ACTION='WRITE')   !HIGH-PASS FILTER
OPEN(UNIT=87, FILE=OUTPUT_PATH87, STATUS='REPLACE', ACTION='WRITE')   !HIGH-PASS FILTER


!OPEN(UNIT=90, FILE=OUTPUT_PATH90, STATUS='REPLACE', ACTION='WRITE')   !FILTER








