PRINT *, "START TO WRITE" 
OPEN(UNIT=20, FILE=OUTPUT_PATH20, ACCESS = 'STREAM', STATUS='REPLACE', ACTION='WRITE')  
OPEN(UNIT=21, FILE=OUTPUT_PATH21, STATUS='REPLACE', ACTION='WRITE')  


OPEN(UNIT=30, FILE=OUTPUT_PATH30, ACCESS = 'STREAM', STATUS='REPLACE', ACTION='WRITE')  
OPEN(UNIT=40, FILE=OUTPUT_PATH40, ACCESS = 'STREAM', STATUS='REPLACE', ACTION='WRITE') 
OPEN(UNIT=41, FILE=OUTPUT_PATH41, STATUS='REPLACE', ACTION='WRITE') 




