PROGRAM CSCAN_GPR_NS

USE MD_BASIC
USE MD_FFT_IFFT
USE MD_FFT_HILBERT

USE MD_INTERPRE

IMPLICIT NONE

!USE GSSI_PROGRAM
INCLUDE "IN_OUT_PATH_CSCAN.h"
INCLUDE "VARIABLES_CSCAN_SUM.h"
INCLUDE "READ_FILES_CSCAN_SUM.h"
INCLUDE "OPEN_WRITE_CSCAN.h"

!POWER SUM
!DO X  = 1, DIS
!DO Y  = 1, TRA 
!      POWER_SUM(X,Y,:) = (B_SCAN_IMAGE6F(X,Y,:) + B_SCAN_IMAGE8(X,Y,:)) /2.0
!END DO 
!END DO 

!AMPLITUDE SUM OF NS AND EW POL.
!DO X  = 1, DIS
!DO Y  = 1, TRA 
!      AMP_SUM(X,Y,:) = (B_SCAN_IMAGE7F(X,Y,:) + B_SCAN_IMAGE9(X,Y,:)) /2.0
!
!END DO 
!END DO 

!EACH IMAGE AVERAGED ON THE BOTH SIDE OF THE FAULT 
!NS

!DO Y  = 1, 12
DO Y  = 13, 21


!DO X = 1, DIS
!DO Z = 1, ROWS

!NS
      AMP_SUM_R(:,1,:) =  AMP_SUM_R(:,1,:) +  B_SCAN_IMAGE7F(:,Y,:) 
!EW
!      AMP_SUM_R(:,1,:) =  AMP_SUM_R(:,1,:) +  B_SCAN_IMAGE9(:,Y,:) 
!NS+EW
!      AMP_SUM_R(:,1,:) =  AMP_SUM_R(:,1,:) +  AMP_SUM(:,Y,:) 

END DO 
 


!ES

! B_SCAN_IMAGE9(X,Y,:)) /2.0
 

!HILBERT TRANSFORM
!HILBERT_A_SCOPE
Y = 1
 
DO X = 1, DIS 
     CALL fft_hilbert(AMP_SUM_R(X,Y,:),ROWS,HILBERT_SIGNAL) 
      HILBERT_AMP_SUM(X,Y,:) = HILBERT_SIGNAL(1,1,:)
END DO



YY = 1


PRINT*,  "COMPLETED TO PICK HOROZIN_1"
PRINT*, "WRITE OUT THE RESULTS"
PRINT*, "WAITING..."


INCLUDE "OUTPUT_A_SCAN.h"               !20
INCLUDE "OUTPUT_B_SCAN.h"               !60, 61  POWERSUM, AMPLITUE_SUM
!INCLUDE "OUTPUT_C_SCAN.h"              !40
INCLUDE "OUTPUT_AMPSUM.h"               !70      AMPSUM POWER
!INCLUDE "OUTPUT_AMPSUM_R.h"               !70      AMPSUM POWER


INCLUDE "OUTPUT_MSR_H.h"                !90, 91
!INCLUDE "OUTPUT_PH.h"                   !92     POWER SUM HORISON
INCLUDE "OUTPUT_AH.h"                   !93     AMPSUM POWER HORISON



END PROGRAM
