!MANUAL EDIT OF THE POSITIN OF SIGNAL
PRINT *,  "MANUAL EDIT OF THE POSITIN OF SIGNAL"

!2023 March 40MHz MIHO GPR

EDIT = 255 


DO Z = 1, (ROWS - EDIT)
   !PRINT *, "Z=",Z
   B_SCAN_IMAGE2(DIS-29, 1 ,Z) = B_SCAN_IMAGE(DIS-29, 1 ,EDIT+Z)
   !B_SCAN_IMAGE2(29, 1 ,Z) = B_SCAN_IMAGE(DIS-29, 1 ,EDIT+Z)
END DO 


EDIT2 = EDIT * 5


B_SCAN_IMAGE2(DIS-18, 2 ,Z) = 0

DO Z = 1, (ROWS - EDIT2)
  B_SCAN_IMAGE2(DIS-18, 2 ,Z) = B_SCAN_IMAGE(DIS-18, 2 ,EDIT2+Z)
   !B_SCAN_IMAGE2(18, 2 ,Z) = B_SCAN_IMAGE(DIS-18, 2 ,EDIT2+Z)
END DO 
