!MANUAL EDIT OF THE POSITIN OF SIGNAL
PRINT *, "MANUAL EDIT OF THE POSITIN OF SIGNAL"


EDIT = 255 

DO Z = 1, (ROWS - EDIT)
   !PRINT *, "Z=",Z
   B_SCAN_IMAGE2(8, 2 ,Z) = B_SCAN_IMAGE(8, 2 ,EDIT+Z)
END DO 

EDIT2 = EDIT * 9 + 8

!B_SCAN_IMAGE(28, 2 ,:) = 0

DO Z = 1, (ROWS - EDIT2)
   B_SCAN_IMAGE2(28, 2 ,Z) = B_SCAN_IMAGE(28, 2 ,EDIT2+Z)
END DO 

