!=======INSTANTNEOUS PHASE=============================================
PRINT *, "PAHSE"
!THIS CODE CALUCUATE THE PHASE FROM -PI/2.0 TO PI/2.0.
DO Z = 1, ROWS
DO Y = 1, LINE
DO X = 1, TRA
   INST_PHASE(X,Y,Z) = ATAN(HILBERT_B_SCAN(X,Y,Z)/B_SCAN_IMAGE8(X,Y,Z))
END DO 
END DO 
END DO 

!SECOND QUADRANT IN COMPLEX DIAGRAM
DO Z = 1, ROWS
DO Y = 1, LINE
DO X = 1, TRA
   IF(HILBERT_B_SCAN(X,Y,Z) > 0.0 .AND. B_SCAN_IMAGE8(X,Y,Z) < 0.0) THEN
      INST_PHASE(X,Y,Z) = INST_PHASE(X,Y,Z) + PI  
   END IF     
END DO 
END DO 
END DO 

!THIRD QUADRANT IN COMPLEX DIAGRAM
DO Z = 1, ROWS
DO Y = 1, LINE
DO X = 1, TRA
   IF(HILBERT_B_SCAN(X,Y,Z) < 0.0 .AND. B_SCAN_IMAGE8(X,Y,Z) < 0.0) THEN
      INST_PHASE(X,Y,Z) = INST_PHASE(X,Y,Z) + PI  
   END IF     
END DO 
END DO 
END DO 

!FORTH QUADRANT IN COMPLEX DIAGRAM
DO Z = 1, ROWS
DO Y = 1, LINE
DO X = 1, TRA
   IF(HILBERT_B_SCAN(X,Y,Z) < 0.0 .AND. B_SCAN_IMAGE8(X,Y,Z) > 0.0) THEN
      INST_PHASE(X,Y,Z) = INST_PHASE(X,Y,Z) + 2.0 * PI  
   END IF     
END DO 
END DO 
END DO 

DO Z = 1, ROWS
DO Y = 1, LINE
DO X = 1, TRA
   INST_PHASE2(X,Y,Z) = INST_PHASE(X,Y,Z) * 180.0/PI
END DO 
END DO 
END DO 

!FOR GNUPLOT
!DO Z = 1, ROWS
!DO Y = 1, LINE
!   WRITE(70,*) (INST_PHASE2(X,1,Z), X = 1, TRA)
!END DO
!END DO 

!FOR PYTHON
DO X = 1, TRA
DO Y = 1, LINE
   WRITE(70,*) (INST_PHASE2(X,Y,Z), Z = 1, ROWS)
END DO
END DO 



PRINT *, "COMPLETE TO PRINT INSTANTNEOUS PHASE"
!==========================================================


!===================INSTANTNEOUS_FREQUENCY==================
DEPTH = 50.0
PER = 16.0
TIME_WIN = 2.0 * DEPTH / ((3*10**8)/sqrt(per))
PRINT *, "TIME_WINDOW",TIME_WIN

SAMPLE_TIME = TIME_WIN / 4096.0

DO Z = 1, ROWS-1
DO Y = 1, LINE
DO X = 1, TRA
   INST_FREQUENCY(X,Y,Z) = ( INST_PHASE2(X,Y,Z+1)-INST_PHASE2(X,Y,Z) ) / SAMPLE_TIME
END DO 
END DO 
END DO 

!FOR GNUPLOT
!DO Z = 1, ROWS
!DO Y = 1, LINE
!   WRITE(71,*) (INST_FREQUENCY(X,Y,Z), X = 1, TRA)
!END DO
!END DO

!FOR PYTHON
DO X = 1, TRA
DO Y = 1, LINE
   WRITE(71,*) (INST_FREQUENCY(X,Y,Z), Z = 1, ROWS)
END DO
END DO


!PRINT *, "COMPLETE TO PRINT INSTANTNEOUS FREQUENCY"
 

