PROGRAM CSCAN_GPR_EW

IMPLICIT NONE

INCLUDE "IN_OUT_PATH_CSCAN_reader.h"
INCLUDE "VARIABLES_CSCAN_EW_reader.h"
INCLUDE "AUTO_READ_FILES_CSCAN_reader.h"

INCLUDE "OPEN_WRITE_CSCAN_reader.h"


PRINT*, "RCD=",ROW_COR_DIS
DO Y = 1, TRA2
   ROW_COR_PIXEL(Y) = INT(ROW_COR_DIS(Y)/0.05)  !5 cm = 0.05 m
END DO 
PRINT*, "RCP=", ROW_COR_PIXEL


DO Y = 1, TRA2
DO X = 1, DIS-ROW_COR_PIXEL(Y)
   B_SCAN_IMAGE4(X+ROW_COR_PIXEL(Y),Y,:) = B_SCAN_IMAGE3(X,Y,:)

END DO 
END DO 

!INCLUDE "OUTPUT_A_SCAN_reader.h"        !20
!INCLUDE "OUTPUT_B_SCAN_reader.h"        !30 
INCLUDE "OUTPUT_C_SCAN_reader.h"        !40
!INCLUDE "OUTPUT_GNSS.h"                !50


END PROGRAM
