
OPEN(UNIT=20, FILE=OUTPUT_PATH20, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
OPEN(UNIT=21, FILE=OUTPUT_PATH21, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
OPEN(UNIT=22, FILE=OUTPUT_PATH22, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
OPEN(UNIT=23, FILE=OUTPUT_PATH23, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE

OPEN(UNIT=30, FILE=OUTPUT_PATH30, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=31, FILE=OUTPUT_PATH31, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=32, FILE=OUTPUT_PATH32, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=33, FILE=OUTPUT_PATH33, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE


OPEN(UNIT=40, FILE=OUTPUT_PATH40, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE
!OPEN(UNIT=40, FILE=OUTPUT_PATH40, ACCESS='STREAM', STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE
OPEN(UNIT=41, FILE=OUTPUT_PATH41, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE


OPEN(UNIT=50, FILE=OUTPUT_PATH50, STATUS='REPLACE', ACTION='WRITE')   !FFT
OPEN(UNIT=60, FILE=OUTPUT_PATH60, STATUS='REPLACE', ACTION='WRITE')   !HILBERT
OPEN(UNIT=70, FILE=OUTPUT_PATH70, STATUS='REPLACE', ACTION='WRITE')   !PHASE








