
!OPEN(UNIT=20,FILE=OUTPUT_PATH20,STATUS='REPLACE'&
!     &, FORMAT='UNFORMATTED', ACCESS = 'STREAM', ACTION='WRITE')

!OPEN(UNIT=30,FILE=OUTPUT_PATH30, ACCESS = 'STREAM', STATUS ='REPLACE',ACTION='WRITE')
OPEN(UNIT=40,FILE=OUTPUT_PATH40, ACCESS = 'STREAM', STATUS ='REPLACE',ACTION='WRITE')


