PROGRAM BSCAN_GPR

IMPLICIT NONE

INCLUDE "IN_OUT_PATH_reader.h"
INCLUDE "VARIABLES_BSCAN_reader.h"
INCLUDE "READ_FILES_BSCAN_reader.h"
!INCLUDE "AUTO_READ_FILES_BSCAN_reader.h"
INCLUDE "OPEN_WRITE_reader.h"
!INCLUDE "OUTPUT_A_SCAN_reader.h"       !30 
INCLUDE "OUTPUT_B_SCAN_reader.h"       !30 
!INCLUDE "OUTPUT_C_SCAN_reader.h"       !40 


END PROGRAM
