!========PATH======================
CHARACTER (LEN=50) :: COMMON_PATH1
CHARACTER (LEN=50) :: COMMON_PATH2
CHARACTER (LEN=120) :: COMMON_PATH3

CHARACTER (LEN=25) :: CWD

CHARACTER (LEN=120) :: INPUT_PATH

CHARACTER (LEN=120) :: OUTPUT_PATH20
CHARACTER (LEN=120) :: OUTPUT_PATH30
!CHARACTER (LEN=120) :: OUTPUT_PATH40


CHARACTER (LEN=50) :: INPUT_NAME
CHARACTER (LEN=50) :: OUTPUT_NAME20
CHARACTER (LEN=50) :: OUTPUT_NAME30
!CHARACTER (LEN=50) :: OUTPUT_NAME40

!=================================


