PROGRAM BSCAN_GPR

USE MD_BACKGROUND
USE MD_MVMEAN
USE MD_STACKING
!USE MD_FFT_IFFT
!USE MD_DFT_IDFT
!USE MD_FFT_HILBERT
!USE MD_CROSS_CORRELATION

IMPLICIT NONE

INCLUDE "T_IN_OUT_PATH.h"
INCLUDE "T_VARIABLES_BSCAN.h"
INCLUDE "T_AUTO_READ_FILES_BSCAN.h"
INCLUDE "T_OPEN_WRITE.h"

!======INITIALIZATION======
!===========================
!ERASE THE UNECESSARY NUMBER. 
!THE NUMBER MEANS THE VALUE OF THE J-1.
B_SCAN_IMAGE3(:,:,1) = 0.0

DO Y = 1, TRA
   DO X = 1, DIS
!CALCUATE THE BACKGROUND
      CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,2001,4000,BGR)

!REMOVE THE BACKGROUND
      B_SCAN_IMAGE4(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR
   END DO
END DO

!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
B_SCAN_IMAGE4(:,:,1) = 1
B_SCAN_IMAGE4(:,:,2) = 1

!MOVING AVERAGE OF THE B SCAN IMAGE TO SUPPRESS THE BACKGROUND

DIS2 = REAL(DIS)/REAL(MV)
DIS3 = INT(DIS2)

ALLOCATE(MV_MEAN_BSCAN(DIS3, 1, ROWS))
ALLOCATE(MV_MEAN_BSCAN2(DIS3, 1, ROWS))
ALLOCATE(STACKED_BSCAN(DIS3, 1, ROWS))


DO Y = 1, TRA
   CALL mv_mean(B_SCAN_IMAGE4(:,Y,:),MV,DIS,ROWS,MV_MEAN_BSCAN)
   MV_MEAN_BSCAN2(:,Y,:) = MV_MEAN_BSCAN(:,1,:)
END DO

   CALL lateral_stacking(MV_MEAN_BSCAN2, DIS3, TRA, ROWS, STACKED_BSCAN)

!DO Z=1,ROWS
!   PRINT *, (MV_MEAN_BSCAN(X,Y,Z), X=1,DIS3)
!END DO

!REMOVE MEAN_ASCAN 
!!   CALL mean_ascan(STACKED_B_SCAN(1,:,:), TRA, ROWS, MEAN_A_SCOPE) 
!!DO Y = 1, TRA
!!   DO Z = 1, ROWS
!!  STACKED_B_SCAN(1, Y, Z) = STACKED_B_SCAN(1, Y, Z) - MEAN_A_SCOPE(1,1,Z)
!!   END DO 
!!END DO


!FFT
!!imag = 0.0   

!!DO Y = 1, TRA
!!    CALL fft(STACKED_B_SCAN(1,Y,:), imag, ROWS, f_real(1,Y,:), f_imag(1,Y,:))
!    CALL ifft(f_real(1,Y,:), f_imag(1,Y,:), ROWS, ifft_real(1,Y,:), ifft_imag(1,Y,:))l
!!END DO

!DO Y = 1, TRA
!    CALL dft(STACKED_A_SCOPE(1,Y,:), imag, ROWS, dft_real(1,Y,:), dft_imag(1,Y,:))
!    CALL idft(dft_real(1,Y,:), dft_imag(1,Y,:), ROWS, idft_real(1,Y,:), idft_imag(1,Y,:)) 
!END DO


!HILBERT TRANSFORMATION
!FIRST SCAN
!!DO Y = 1, TRA
!!      CALL fft_hilbert(B_SCAN_IMAGE4(1,Y,:), ROWS, HILBERT_SIGNAL)
 !!     HILBERT_B_SCAN(1,Y,:) = HILBERT_SIGNAL(1,1,:) 
!!END DO

!STACKED SCAN WITH THE AMOUNT OF THE DIS
!!DO Y = 1, TRA
!!      CALL fft_hilbert(STACKED_B_SCAN(1,Y,:), ROWS, HILBERT_STACKED_SIGNAL)
!!      HILBERT_STACKED_B_SCAN(1,Y,:) = HILBERT_STACKED_SIGNAL(1,1,:) 
!!END DO

!CROSS CORRELATION
!! crrl = 0.0 
!!    CALL cross_corl(B_SCAN_IMAGE4(1,1,:), &
!!                    B_SCAN_IMAGE4(1,1,:), ROWS,crrl)
    

!    CALL cross_corl(HILBERT_STACKED_SIGNAL(1,1,:), &
!                    HILBERT_STACKED_SIGNAL(1,1,:), ROWS,crrl)

INCLUDE "T_OUTPUT_A_SCOPE.h"                  !20
INCLUDE "T_OUTPUT_B_SCAN.h"                  !21 
!INCLUDE "T_OUTPUT_HILBERT_B_SCAN.h"          !22
!INCLUDE "T_OUTPUT_HILBERT_STACKED_B_SCAN.h"   !23

!INCLUDE "T_OUTPUT_FFT_STACKED_A_SCOPE.h"
!INCLUDE "T_OUTPUT_DFT_STACKED_A_SCOPE.h"
!INCLUDE "T_OUTPUT_CRRL.h"


DEALLOCATE(MV_MEAN_BSCAN)
DEALLOCATE(MV_MEAN_BSCAN2)
DEALLOCATE(STACKED_BSCAN)

END PROGRAM
