PROGRAM BSCAN_GPR

USE MD_BACKGROUND
USE MD_MVMEAN
USE MD_STACKING
USE MD_MEAN_ASCAN
USE MD_FFT_IFFT
!USE MD_DFT_IDFT
USE MD_FFT_HILBERT
!USE MD_CROSS_CORRELATION

IMPLICIT NONE

INCLUDE "T_IN_OUT_PATH.h"
INCLUDE "T_VARIABLES_BSCAN.h"
INCLUDE "T_AUTO_READ_FILES_BSCAN.h"
INCLUDE "T_OPEN_WRITE.h"

!======INITIALIZATION======
!===========================
!ERASE THE UNECESSARY NUMBER. 
!THE NUMBER MEANS THE VALUE OF THE J-1.
B_SCAN_IMAGE3(:,:,1) = 0.0

DO Y = 1, TRA
   DO X = 1, DIS
!CALCUATE THE BACKGROUND
      CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,2001,4000,BGR)

!REMOVE THE BACKGROUND
      B_SCAN_IMAGE4(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR
   END DO
END DO

!TO MAKE THE GRAPH STABLE
!I MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG
!THEN, I ASSIGNED 1.
B_SCAN_IMAGE4(:,:,1) = 1
B_SCAN_IMAGE4(:,:,2) = 1

!MOVING AVERAGE OF THE B SCAN IMAGE TO SUPPRESS THE BACKGROUND

DIS2 = REAL(DIS)/REAL(MV)
DIS3 = INT(DIS2)

ALLOCATE(MV_MEAN_BSCAN(DIS3, 1, ROWS))
ALLOCATE(MV_MEAN_BSCAN2(DIS3, TRA, ROWS))

DO Y = 1, TRA
   CALL mv_mean(B_SCAN_IMAGE4(:,Y,:),MV,DIS,ROWS,MV_MEAN_BSCAN)
   MV_MEAN_BSCAN2(:,Y,:) = MV_MEAN_BSCAN(:,1,:)
END DO

DEALLOCATE(MV_MEAN_BSCAN)

DO Y = 1, TRA
   DO X = 1, DIS3
!CALCUATE THE BACKGROUND
      CALL background(MV_MEAN_BSCAN2(X,Y,:),ROWS,2001,4000,BGR)

!REMOVE THE BACKGROUND
      MV_MEAN_BSCAN2(X,Y,:) = MV_MEAN_BSCAN2(X,Y,:) + BGR
 !     PRINT *, BGR
   END DO
END DO



ALLOCATE(STACKED_BSCAN(DIS3, 1, ROWS))
ALLOCATE(STACKED_BSCAN2(DIS3, 1, ROWS))

!REMOVE_MOVING_AVERAGE
   CALL lateral_stacking(MV_MEAN_BSCAN2, DIS3, TRA, ROWS, STACKED_BSCAN)
   PRINT *, "DIS3=",DIS3 
 
!REMOVE MEAN_ASCAN 
!!   CALL mean_ascanx(STACKED_BSCAN(:,1,:), DIS3, ROWS, MEAN_A_SCOPE) 
!!DO X = 1, DIS3
!!   DO Z = 1, ROWS
!!  STACKED_BSCAN(X, 1, Z) = STACKED_BSCAN(X, 1, Z) - MEAN_A_SCOPE(1,1,Z)
!!   END DO 
!!END DO


!FFT
ALLOCATE(f_real(DIS3, 1, ROWS))
ALLOCATE(f_imag(DIS3, 1, ROWS))
ALLOCATE(f_phase(DIS3, 1, ROWS))

imag = 0.0   

DO X= 1, DIS3
    CALL fft(STACKED_BSCAN(X,1,:), imag, ROWS, f_real(X,1,:), f_imag(X,1,:))
!    CALL ifft(f_real(1,Y,:), f_imag(1,Y,:), ROWS, ifft_real(1,Y,:), ifft_imag(1,Y,:))l
END DO

!DO Y = 1, TRA
!    CALL dft(STACKED_A_SCOPE(1,Y,:), imag, ROWS, dft_real(1,Y,:), dft_imag(1,Y,:))
!    CALL idft(dft_real(1,Y,:), dft_imag(1,Y,:), ROWS, idft_real(1,Y,:), idft_imag(1,Y,:)) 
!END DO


!HILBERT TRANSFORMATION
!FIRST SCAN
!!DO X = 1, DIS3
!!     CALL fft_hilbert(B_SCAN_IMAGE4(X,1,:), ROWS, HILBERT_SIGNAL)
!!     HILBERT_B_SCAN(X,1,:) = HILBERT_SIGNAL(1,1,:) 
!!END DO

!STACKED SCAN WITH THE AMOUNT OF THE DIS
ALLOCATE(HILBERT_STACKED_B_SCAN(DIS3,TRA,ROWS))

DO X = 1, DIS3
      CALL fft_hilbert(STACKED_BSCAN(X,1,:), ROWS, HILBERT_STACKED_SIGNAL)
      HILBERT_STACKED_B_SCAN(X,1,:) = HILBERT_STACKED_SIGNAL(1,1,:) 
END DO

!CROSS CORRELATION
!! crrl = 0.0 
!!    CALL cross_corl(B_SCAN_IMAGE4(1,1,:), &
!!                    B_SCAN_IMAGE4(1,1,:), ROWS,crrl)
    

!    CALL cross_corl(HILBERT_STACKED_SIGNAL(1,1,:), &
!                    HILBERT_STACKED_SIGNAL(1,1,:), ROWS,crrl)

INCLUDE "T_OUTPUT_A_SCOPE.h"                  !20
INCLUDE "T_OUTPUT_B_SCAN.h"                  !21 
!INCLUDE "T_OUTPUT_HILBERT_B_SCAN.h"          !22
INCLUDE "T_OUTPUT_HILBERT_STACKED_B_SCAN.h"   !23

INCLUDE "T_OUTPUT_FFT.h"      !24
!INCLUDE "T_OUTPUT_DFT_STACKED_A_SCOPE.h"
!INCLUDE "T_OUTPUT_CRRL.h"


DEALLOCATE(MV_MEAN_BSCAN2)
DEALLOCATE(STACKED_BSCAN)
DEALLOCATE(STACKED_BSCAN2)
DEALLOCATE(f_real)
DEALLOCATE(f_imag)
DEALLOCATE(f_phase)
DEALLOCATE(HILBERT_STACKED_B_SCAN)

END PROGRAM
