Program OPEN_GSSI
USE MD_BACKGROUND
USE MD_STACKING
!USE MD_FFT_HILBERT

IMPLICIT NONE

INCLUDE "IN_OUT_PATH.h"
INCLUDE "VARIABLES.h"
INCLUDE "AUTO_READ_FILES.h"
INCLUDE "OPEN_WRITE.h"

!======INITIALIZATION=======
!DIS = 0
!B_SCAN_IMAGE = 0
!B_SCAN_IMAGE2 = 0.0
!B_SCAN_IMAGE3 = 0.0
!INTENSITY = 0.0
!===========================

!READ(10) HEADER,B_SCAN_IMAGE

!INTEGER => REAL*8

!CALCUATE THE BACKGROUND
DO Y = 1, TRA
    DO X=1,DIS
        CALL background(B_SCAN_IMAGE3(X,Y,:),ROWS,2001,4000,BGR)

!REMOVE THE BACKGROUND
        B_SCAN_IMAGE4(X,Y,:) = B_SCAN_IMAGE3(X,Y,:) - BGR
    END DO
END DO

!TO MAKE THE GRAPH STABLE
!IF MADE IT 1, IT COULD MAKE AN ERROR WHEN CALCULATING LOG.
!THEN, I ASSIGNED 1.

B_SCAN_IMAGE4(:,:,1) = 1.0
B_SCAN_IMAGE4(:,:,2) = 1.0

!STACKING THE A_SCOPE TO SUPPRESS THE BACKGROUND.
!N_STACK IS THE NUMBER OF THE STACKING.
!YOU CAN CALCULATE THE NUMBER OF THE A_SCOPE, DIS2, 
!BY DIVING THE DIS BY N_STCACK.

DO Y = 1, TRA
DO X = 1, DIS2

       S = 1 + N_STACK * (X-1)
       E = N_STACK + N_STACK * (X-1)
   
!       PRINT *, S,E, N_STACK
     CALL stacking(B_SCAN_IMAGE4(S:E, Y, :), ROWS, N_STACK, STACKED_A_SCOPE)
       STACKED_B_SCAN(X,Y,:) = STACKED_A_SCOPE(1,1,:)
END DO
END DO

DO Y = 1, TRA
DO X = 1, DIS2
!       PRINT *,  MAXLOC(STACKED_B_SCAN(X,1,:)) 
    
!    LAYER(X,1,1) = 90.0/4096.0  * MAXLOC(STACKED_B_SCAN(X,1,:),1) 
    LAYER(X,Y,1) =  MAXLOC(STACKED_B_SCAN(X,Y,:),1) 

END DO 
END DO

INCLUDE "OUTPUT_A_SCOPE.h"
INCLUDE "OUTPUT_LAYER.h"

END PROGRAM
