MODULE MD_REMOVE_MEAN
IMPLICIT NONE

CONTAINS

  SUBROUTINE remove_mean(B_SCAN_IMAGE,ROWS,DIS,MEAN) 
  IMPLICIT NONE

  INTEGER :: d !depth

  INTEGER, INTENT(IN) :: ROWS
  INTEGER, INTENT(IN) :: DIS 
  REAL*8, DIMENSION(DIS, 1, 1), INTENT(IN) :: B_SCAN_IMAGE
  
  REAL*8 :: MEAN
!  REAL*8, DIMENSION(1, 1, ROWS) :: IMAGE_MEAN
!  REAL*8, DIMENSION(DIS, 1, 1), INTENT(OUT) :: IMAGE_AFTER_REMOVE_BG
  
     MEAN = SUM(B_SCAN_IMAGE(:,1,1)) / REAL(SIZE(B_SCAN_IMAGE(:,1,1)))


!  DO d = 1, ROWS
!     IMAGE_MEAN(d,1) = SUM(B_SCAN_IMAGE(:,1,1)) / REAL(SIZE(B_SCAN_IMAGE(:,1,1)))
!     IMAGE_AFTER_REMOVE_BG(d,1,1) = B_SCAN_IMAGE(d,1,1) - IMAGE_MEAN(d,1) 
!   END DO

  END SUBROUTINE remove_mean

END MODULE MD_REMOVE_MEAN


