MODULE p_determination
IMPLICIT NONE
 
CONTAINS

  SUBROUTINE integer2binary(I,NU,B) 
  IMPLICIT NONE
    INTEGER, INTENT(IN) :: I
    INTEGER, INTENT(IN) :: NU
    INTEGER, DIMENSION (NU), INTENT(OUT) :: B
    INTEGER :: C,J,L

    B = 0 
    J = I
    
    DO C=NU,1,-1
    
       IF(MOD(J,2)==0) THEN
         B(C) = 0    
       ELSE
         B(C) = 1
       END IF

       J=J/2 !NOTICE THE USE OF TRUNCATED RESULT

       IF (J==0) THEN
          EXIT
       END IF

    END DO
 
  END SUBROUTINE 
    
  SUBROUTINE scale2right(K_BINARY,NU1,K_BINARY_SCALED)
    INTEGER, INTENT(IN) :: NU1
    INTEGER, DIMENSION(:) :: K_BINARY
    INTEGER, DIMENSION(:), INTENT(OUT) :: K_BINARY_SCALED
    INTEGER :: I,J,K,T,L
   
    I=0
    J=1
    T=0
     
    T=SIZE(K_BINARY)-NU1
   
    DO J=1,T
     
       K_BINARY_SCALED(J+NU1)=K_BINARY(J)       
    
    END DO

    DO L=1,NU1
       K_BINARY_SCALED(L)=0
    END DO

  END SUBROUTINE 

  SUBROUTINE reversed_binary(K_BINARY_SCALED,K_BINARY_SCALED_REVERSED)
  IMPLICIT NONE

  INTEGER, DIMENSION(:) :: K_BINARY_SCALED
  INTEGER, DIMENSION(:), INTENT(OUT) :: K_BINARY_SCALED_REVERSED
  INTEGER :: I,NU
     
        DO I=1,SIZE(K_BINARY_SCALED)
       
          K_BINARY_SCALED_REVERSED(SIZE(K_BINARY_SCALED)+1-I) = K_BINARY_SCALED(I)
       
        END DO
    
  END SUBROUTINE


  SUBROUTINE binary2integer(K_BINARY_SCALED_REVERSED, P_INTEGER)
  IMPLICIT NONE

  INTEGER,DIMENSION(:) :: K_BINARY_SCALED_REVERSED
  INTEGER, INTENT(OUT) :: P_INTEGER
  INTEGER :: I,J

  P_INTEGER=0
   
    DO J=1,SIZE(K_BINARY_SCALED_REVERSED)

       P_INTEGER=P_INTEGER+K_BINARY_SCALED_REVERSED(J)*2**(SIZE(K_BINARY_SCALED_REVERSED)-J) 

    END DO

  END SUBROUTINE

END MODULE p_determination


