PROGRAM CSCAN_GPR_EW

IMPLICIT NONE

INCLUDE "IN_OUT_PATH_CSCAN_reader.h"
INCLUDE "VARIABLES_CSCAN_EW_reader.h"
INCLUDE "AUTO_READ_FILES_CSCAN_reader.h"

INCLUDE "OPEN_WRITE_CSCAN_reader.h"

INCLUDE "OUTPUT_A_SCAN_reader.h"        !20
INCLUDE "OUTPUT_B_SCAN_reader.h"        !30 
INCLUDE "OUTPUT_C_SCAN_reader.h"        !40

END PROGRAM
