
G = 2
DO P =1, TRACE(G) 
   B_SCAN_IMAGE3F(G-1,TRACE(G)-P+1,:) = B_SCAN_IMAGE3(G-1,P,:) 
END DO 

G = 3
DO P =1, TRACE(G) 
   B_SCAN_IMAGE3F(G-1,TRACE(G)-P+1,:) = B_SCAN_IMAGE3(G-1,P,:) 
END DO 

G = 4
DO P =1, TRACE(G) 
   B_SCAN_IMAGE3F(G-1,TRACE(G)-P+1,:) = B_SCAN_IMAGE3(G-1,P,:) 
END DO 


!MANUAL EDITING (REASON, THOSE LINES ARE TOO WIERD!)
!COL_COR_PIXEL2(32) =  INT(COL_COR_PIXEL2(31) +  COL_COR_PIXEL2(33) / 2.0)  
!COL_COR_PIXEL2(50) =  INT(COL_COR_PIXEL2(49) +  COL_COR_PIXEL2(51) / 2.0)
!COL_COR_PIXEL2(76) =  INT(COL_COR_PIXEL2(75) +  COL_COR_PIXEL2(77) / 2.0)  
!COL_COR_PIXEL2(84) =  INT(COL_COR_PIXEL2(83) +  COL_COR_PIXEL2(85) / 2.0) 



