
OPEN(UNIT=20, FILE=OUTPUT_PATH1, STATUS='REPLACE', ACTION='WRITE')   !A_SCOPE
OPEN(UNIT=21, FILE=OUTPUT_PATH2, STATUS='REPLACE', ACTION='WRITE')   !B_SCAN_IMAGE
OPEN(UNIT=22, FILE=OUTPUT_PATH3, STATUS='REPLACE', ACTION='WRITE')   !C_SCAN_IMAGE
OPEN(UNIT=23, FILE=OUTPUT_PATH4, STATUS='REPLACE', ACTION='WRITE')   !3D_CUBE_IMAGE
OPEN(UNIT=24, FILE=OUTPUT_PATH5, STATUS='REPLACE', ACTION='WRITE')   !HILBERT_3D_CUBE_IMAGE



