OPEN(UNIT=20,FILE=OUTPUT_PATH1,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=21,FILE=OUTPUT_PATH2,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=22,FILE=OUTPUT_PATH3,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=23,FILE=OUTPUT_PATH4,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=24,FILE=OUTPUT_PATH5,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=25,FILE=OUTPUT_PATH6,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=26,FILE=OUTPUT_PATH7,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=27,FILE=OUTPUT_PATH8,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=28,FILE=OUTPUT_PATH9,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=29,FILE=OUTPUT_PATH10,STATUS='REPLACE',ACTION='WRITE')




