OPEN(UNIT=20,FILE=OUTPUT_PATH20,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=21,FILE=OUTPUT_PATH21,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=22,FILE=OUTPUT_PATH22,STATUS='REPLACE',ACTION='WRITE')


OPEN(UNIT=30,FILE=OUTPUT_PATH30,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=31,FILE=OUTPUT_PATH31,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=32,FILE=OUTPUT_PATH32,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=33,FILE=OUTPUT_PATH33,STATUS='REPLACE',ACTION='WRITE')

OPEN(UNIT=40,FILE=OUTPUT_PATH40,STATUS='REPLACE',ACTION='WRITE')
!OPEN(UNIT=41,FILE=OUTPUT_PATH41,STATUS='REPLACE',ACTION='WRITE')


OPEN(UNIT=50,FILE=OUTPUT_PATH50,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=51,FILE=OUTPUT_PATH51,STATUS='REPLACE',ACTION='WRITE')


OPEN(UNIT=60,FILE=OUTPUT_PATH60,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=61,FILE=OUTPUT_PATH61,STATUS='REPLACE',ACTION='WRITE')

OPEN(UNIT=70,FILE=OUTPUT_PATH70,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=71,FILE=OUTPUT_PATH71,STATUS='REPLACE',ACTION='WRITE')

OPEN(UNIT=80,FILE=OUTPUT_PATH80,STATUS='REPLACE',ACTION='WRITE')
OPEN(UNIT=81,FILE=OUTPUT_PATH81,STATUS='REPLACE',ACTION='WRITE')




