PRINT *, "START TO WRITE" 
OPEN(UNIT=20, FILE=OUTPUT_PATH20, STATUS='REPLACE', ACTION='WRITE')  
OPEN(UNIT=30, FILE=OUTPUT_PATH30, STATUS='REPLACE', ACTION='WRITE')  
OPEN(UNIT=31, FILE=OUTPUT_PATH31, STATUS='REPLACE', ACTION='WRITE')  
OPEN(UNIT=40, FILE=OUTPUT_PATH40, STATUS='REPLACE', ACTION='WRITE') 
OPEN(UNIT=50, FILE=OUTPUT_PATH50, STATUS='REPLACE', ACTION='WRITE') 



